Script started on 2017年03月17日 (週五) 15時19分08秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami.;[K[K;pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -1[Kl
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone[Kneh[K https://github.com/xxSTORYxx/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月17日 (週五) 15時58分29秒
