Script started on 2017年03月17日 (週五) 15時19分08秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami.;[K[K;pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -1[Kl
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clonehttps;[K://github [C[1@ [1P[C[1@ [C[C[C[C[C[C[C[C[C[C[C[C[C[C. c o m / x x S T O R Y x x / l a b 1 . g i t 
Cloning into 'lab1'...
fatal: unable to access 'https://github.com/xxSTORYxx/lab1.git/': Could not resolve host: github.com
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git cloe[Kneh[K https://github.com/xxSTORYxx/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月17日 (週五) 15時58分29秒
